gantt
    title Veille x Sprints CATASTERRE
    dateFormat YYYY-MM-DD
    axisFormat %d/%m
    section Sprint1
    US-1 US-2 US-5           :s1, 2026-06-01, 14d
    FORM-T0 PROC-T2          :s1f, 2026-06-01, 14d
    section Sprint2
    US-3 US-7 TEST-T1 T2     :s2, 2026-06-15, 14d
    Formation T-DI1 T-RA1    :s2f, 2026-06-15, 14d
    section Sprint3
    US-8 US-10 TEST-T3       :s3, 2026-06-29, 14d
    section Sprint4plus
    US-6 US-9 US-11          :s4, 2026-07-13, 28d
